# Résoudre react_native_pods.rb avec node pour permettre le hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Inclure le script de configuration de react-native-permissions
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native-permissions/scripts/setup.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuration du Pod avec des Frameworks liés #{linkage}".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'stockPilot' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Un chemin absolu vers la racine de votre application.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Configurer les permissions requises
  setup_permissions([
    'Camera',
    # Ajoutez d'autres permissions si nécessaire
  ])

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
